version: "3"

services:
    builder:
        image: node:8.4.0-alpine
        ports:
            - 4200:4200
        volumes:
            - ./project:/host
        working_dir: /host
        command: sh -c "npm install && ln -sf /host/node_modules/.bin/* /usr/local/bin/ && ng server --host 0.0.0.0"